---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  StyleGuideCopsOnly: true
  TargetRubyVersion: 2.3
  Exclude:
    - spec/dummy/db/schema.rb
    - vendor/bundle/**/*
    - gemfiles/vendor/**/*

Metrics/ParameterLists:
  Max: 5

Naming/FileName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
